export const QUOTES: string[] = [
  "Turn minutes into momentum.",
  "Focus is the art of knowing what to ignore.",
  "Small steps, taken daily, become giant leaps.",
  "Discipline is choosing what you want most over what you want now.",
  "You don't have to be extreme, just consistent.",
  "The successful warrior is the average person with laser-like focus.",
  "Concentrate all your thoughts upon the work at hand.",
  "Where focus goes, energy flows.",
  "Amateurs sit and wait for inspiration; the rest of us just get to work.",
  "Deep work is the superpower of the 21st century.",
  "Motivation gets you going; discipline keeps you growing.",
  "Do the hard jobs first. The easy jobs will take care of themselves.",
  "The way to get started is to quit talking and begin doing.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Don't watch the clock; do what it does. Keep going.",
  "Simplicity is the ultimate sophistication.",
  "Action is the foundational key to all success.",
  "Fall in love with the process and the results will come.",
  "Slow is smooth. Smooth is fast.",
  "You are what you repeatedly do.",
  "Progress, not perfection.",
  "The secret of getting ahead is getting started.",
  "Focus on being productive instead of busy.",
  "Well done is better than well said.",
  "One session at a time.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Energy and persistence conquer all things.",
  "Do something today that your future self will thank you for.",
  "Great things are done by a series of small things brought together.",
  "Quality is not an act, it is a habit.",
  "Direction is more important than speed.",
  "Focus is a matter of deciding what things you're not going to do.",
  "It always seems impossible until it's done.",
  "You will never always be motivated, so you must learn to be disciplined.",
  "Push yourself, because no one else is going to do it for you.",
  "Little by little, a little becomes a lot.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "Wake up with determination, go to bed with satisfaction.",
  "Dreams don't work unless you do.",
  "Don't limit your challenges; challenge your limits.",
  "Doing is better than perfect.",
  "One day or day one — you decide.",
  "Every accomplishment starts with the decision to try.",
  "Winners focus on winning, losers focus on winners.",
  "The expert in anything was once a beginner.",
  "Consistency is what transforms average into excellence.",
  "You don't rise to the level of your goals, you fall to the level of your systems.",
  "Attention is the rarest and purest form of generosity.",
  "The mind is everything. What you think, you become.",
  "Focus like a lion. Move like a wolf. Rest like an owl.",
];

export function randomQuote() {
  return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}
